services:
  postgres-db:
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=postgres@example.com"
      - PGADMIN_DEFAULT_PASSWORD
      - "PGADMIN_LISTEN_PORT=5050"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:5050
  backend:
    environment:
      - BUILD=dev
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
  webserver:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default-dev.conf:/etc/nginx/conf.d/default.conf
  redis-server:
    ports:
      - 6379:6379
volumes:
  pgadmin-data:

