services:
  postgres-db:
    container_name: postgres
    image: "postgres:15"
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: backend
    environment:
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
  webserver:
    container_name: webserver
    build: .
    ports:
      - 80:80
  redis-server:
    container_name: redis_server
    image: redis
    volumes:
      - redis-data:/data
volumes:
  db-data:
  redis-data: